version: '3'

services:

  db:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    restart: always
    env_file:
      - Backend/.env

  adminer:
    container_name: adminer
    image: 'adminer:latest'
    ports:
      - 8080:8080

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./backend/uploads:/backend/uploads
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - MODE=prod
      - PORT=5000
      - BACKEND_HOST=http://10.11.13.12:5000
      - FRONTEND_HOST=http://10.11.13.12:3000

  frontend:
    container_name: frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - MODE=prod
      - PORT=3000
      - BACKEND_HOST=http://10.11.13.12:5000